# Generated by Django 4.0.6 on 2024-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='musica',
            name='releaseDate',
            field=models.CharField(max_length=30),
        ),
    ]
