# Generated by Django 4.0.6 on 2024-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBandas', '0002_alter_album_releasedate_alter_musica_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='releaseDate',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='musica',
            name='ano_lancamento',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
