# Generated by Django 4.0.6 on 2024-04-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFestivais', '0002_festival_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='festival_covers/'),
        ),
    ]
